apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDeploymentEnforceLabels
metadata:
  name: deployment-enforce-labels
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Deployment"]
  parameters:
    labels: {{ .Values.labels }}
